# config/services.yaml

services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         false

  # Toutes vos classes dans src/, sauf certains sous-dossiers
  App\:
    resource: '../src/*'
    exclude:
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
