# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Désactive la sécurité sur le profiler/debug
    dev:
      pattern: ^/_(profiler|wdt)
      security: false

    # Pare-feu principal : couvre TOUT le site, y compris /login et /register
    main:
      pattern: ^/
      provider: app_user_provider
      lazy: true
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
      logout:
        path:   app_logout
        target: /

  access_control:
    # impératif : autoriser l’anonyme *avant* toute autre règle
    - { path: ^/register$, roles: PUBLIC_ACCESS }
    - { path: ^/login$,    roles: PUBLIC_ACCESS }

    # puis restreindre la partie admin
    - { path: ^/article,   roles: ROLE_ADMIN }
